1.	Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np

In [2]:
arr1 = np.array([[1,2,3],[2,5,8],[3,6,9]])
arr2 = np.array([[6,5,4],[7,8,9],[7,6,9]])

In [3]:
# addition of two matrices 

print(arr1+arr2)

[[ 7  7  7]
 [ 9 13 17]
 [10 12 18]]


2.	Write a Python Program to Multiply Two Matrices?


In [5]:
arr1.dot(arr2)

array([[ 41,  39,  49],
       [103,  98, 125],
       [123, 117, 147]])

3.	Write a Python Program to Transpose a Matrix?

In [6]:
np.transpose(arr1)

array([[1, 2, 3],
       [2, 5, 6],
       [3, 8, 9]])

4.	Write a Python Program to Sort Words in Alphabetic Order?

In [7]:
my_str = "Hello this Is an Example With cased letters"

In [8]:
word = my_str.split()

In [9]:
word

['Hello', 'this', 'Is', 'an', 'Example', 'With', 'cased', 'letters']

In [10]:
word.sort()

In [11]:
for i in word :
    print(i)

Example
Hello
Is
With
an
cased
letters
this


In [12]:
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

In [13]:
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Hello he said and went
